Important fixes
JWManagement/JWManagement pull request #441
Opened 2022-06-28 11:29 UTC by tim-antkowiak

Most important fixes:
- Implement new data privacy policy all users has to accept
- Fix broken links
- ....

2022-06-28 11:49 UTC, aloosen requested changes

2022-06-28 11:49 UTC, aloosen commented on client/views/common/footer/footer.js
> +    if ((navigator.language || navigator.userLanguage) === "de-DE") {
exludes de, de-AT, de-CH, de-LI, de-LU, etc.
possible solution: 
`if ((navigator.language || navigator.userLanguage || '').startsWith('de'))`

2022-06-28 11:49 UTC, aloosen commented on imports/ui/signUp/signUp.js
> +    if ((navigator.language || navigator.userLanguage) === "de-DE") {
same as in footer.js:

`if ((navigator.language || navigator.userLanguage || '').startsWith('de'))`

2022-06-28 12:06 UTC, tim-antkowiak commented on client/views/common/footer/footer.js
> +    if ((navigator.language || navigator.userLanguage) === "de-DE") {
```suggestion
    if ((navigator.language || navigator.userLanguage || '').startsWith('de')) {
```

2022-06-28 12:09 UTC, tim-antkowiak commented on imports/ui/signUp/signUp.js
> +    if ((navigator.language || navigator.userLanguage) === "de-DE") {
```suggestion
    if ((navigator.language || navigator.userLanguage || '').startsWith('de')) {
```

2022-07-02 03:30 UTC, aloosen commented on imports/ui/dashboard/AcceptGdpr.jsx
> +    Meteor.call('updateProfile', 'acceptedGdpr', true);
This doesn't seem to be persistent. When I change my user language, for example, the popup reappears. Is that intended?

2022-07-02 19:06 UTC, tim-antkowiak commented on imports/ui/dashboard/AcceptGdpr.jsx
> +    Meteor.call('updateProfile', 'acceptedGdpr', true);
Good catch! Maybe it gets overwritten somewhere.. Need to check that.

2022-07-11 17:10 UTC, tim-antkowiak commented
As discussed in our meeting I removed the popup related commits.
Shall we already merge or should we use this PR also for #451 ?

2022-07-11 17:16 UTC, tim-antkowiak commented on client/views/common/footer/footer.js
> +  getLanguage: () => {
Should we look for the selected language first here?

I'm thinking for example about someone on an English OS or browser who selected German in the user settings of JW Management. He wants to see the pages in German I assume.

2022-07-11 17:16 UTC, tim-antkowiak commented on client/views/common/footer/footer.js
> +})
```suggestion
})

```

2022-07-23 13:06 UTC, tim-antkowiak commented
Would anybody be able to test and/or review the recent changes?

2022-07-25 15:51 UTC, aloosen commented
will do later today

2022-08-02 08:43 UTC, tim-antkowiak commented on imports/ui/signUp/signUp.html
> +              <a href="{{pathFor 'signUp' language=langTag}}" target="blank">{{_ 'signUp.privacyPolicy'}}</a>.
```suggestion
              <a href="{{pathFor 'privacy' language=langTag}}" target="blank">{{_ 'signUp.privacyPolicy'}}</a>.
```

2022-08-02 08:43 UTC, tim-antkowiak commented on imports/ui/signUp/signUp.html
> +              <a href="{{pathFor 'signUp' language=langTag}}" target="blank">{{_ 'signUp.terms'}}</a>
```suggestion
              <a href="{{pathFor 'terms' language=langTag}}" target="blank">{{_ 'signUp.terms'}}</a>
```

2022-08-02 08:43 UTC, tim-antkowiak commented on imports/ui/signUp/signUp.html
> +              <a href="{{pathFor 'signUp' language=langTag}}" target="blank">{{_ 'signUp.privacyPolicy'}}</a>.
But even with these changes I get some strange behavior.. The privacy link always points to the german privacy page, no matter what language I selected. 
The terms link changes with the selected language and works for german but not for any other languages because it always points to the full language code like 'en-US'. And even for non en/de languages it points to this specific language like /it/terms.

Any ideas?

2022-08-02 08:43 UTC, tim-antkowiak commented on client/views/common/footer/footer.js
> +  getLanguage: () => i18next.languages.find(lang => ['de', 'en'].find(lng => lang === lng)) || 'en'
Do we even need to check for 'en' since the only language code where we don't want to show the English page is 'de'?

2022-08-02 08:43 UTC, tim-antkowiak commented on imports/ui/signUp/signUp.html
> +              <a href="{{pathFor 'signUp' language=langTag}}" target="blank">{{_ 'signUp.privacyPolicy'}}</a>.
Maybe just using the same method as for the footer?

2022-08-02 08:49 UTC, tim-antkowiak commented
@aloosen I think after we addressed the latest changes we can merge :)

2022-08-05 15:19 UTC, aloosen commented
I agree. Let's go ahead 👍

2022-10-16 13:11 UTC, merged