440 translate privacy
JWManagement/JWManagement pull request #453
Opened 2022-07-11 20:53 UTC by studiozandra

Feature added for [issue #440](https://github.com/JWManagement/JWManagement/issues/440):
===

  1. **English Privacy Policy:** machine translation via DeepL.com -- english has been proofread by me.
     **Tested by changing browser language in Chrome on Linux :** the correct URL matching the browser language is shown 

![Peek 2022-07-11optimized](https://user-images.githubusercontent.com/17014512/178354712-d70c241f-86cd-4ae1-8075-4c760b42f492.gif)

gif made using https://github.com/phw/peek 
and 
https://ezgif.com/optimize

2022-07-12 06:45 UTC, tim-antkowiak commented
Hey @studiozandra thank you so much for contributing!

We made some changes yesterday on the develop branch, sorry for the confusion.

To fix the commits you need to rebase your branch again on the current develop branch:

```
# Add the remote, call it "upstream":
git remote add upstream git@github.com:JWManagement/JWManagement.git

# Fetch all the branches of that remote into remote-tracking branches
git fetch upstream

# Make sure that you're on your branch:
git checkout 440-translate-privacy

# Rewrite your branch so that any commits of yours that
# aren't already in upstream/master are replayed on top of that
# other branch:
git rebase upstream/develop

# (Force) Push your branch
git push origin 440-translate-privacy --force
```

Could you try these steps?

2022-07-12 14:51 UTC, studiozandra commented
Thank you very kindly! I have run those commands. Still a couple of other commits in there 🤔

2022-07-12 15:24 UTC, tim-antkowiak commented
Yea, that were the commits we removed from the develop branch yesterday. I just updated your branch. 
Make sure to do a `git fetch` and maybe a `git reset --hard origin/440-translate-privacy` to get the updated branch on your local setup.

2022-07-19 07:44 UTC, tim-antkowiak requested changes

2022-07-19 07:44 UTC, tim-antkowiak commented on client/views/common/footer/footer.tpl.jade
> +		a(href='/{{getLanguage}}/privacy' target='blank') Privacy
```suggestion
		a(href='/{{getLanguage}}/privacy' target='blank') {{_ "signUp.privacyPolicy"}}
```

2022-07-19 07:44 UTC, tim-antkowiak commented on client/views/common/footer/footer.tpl.jade
>  		a(href='/{{getLanguage}}/terms' target='blank') Terms
```suggestion
		a(href='/{{getLanguage}}/terms' target='blank') {{_ "signUp.terms"}}
```

2022-07-19 07:46 UTC, tim-antkowiak approved these changes

2022-07-19 07:47 UTC, merged